name: matomo_tracker
description: A fully cross-platform wrap of the Matomo tracking client for
  Flutter, using the Matomo API.
version: 3.1.0
homepage: https://github.com/Floating-Dartists/matomo-tracker
repository: https://github.com/Floating-Dartists/matomo-tracker
issue_tracker: https://github.com/Floating-Dartists/matomo-tracker/issues

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  clock: ^1.1.1
  device_info_plus: ">=8.0.0 <10.0.0"
  flutter:
    sdk: flutter
  http: ^0.13.5
  package_info_plus: ">=3.0.0 <4.0.0"
  shared_preferences: ^2.0.18
  uuid: ^3.0.7

dev_dependencies:
  fd_lints: ^1.0.2
  flutter_test:
    sdk: flutter
  meta: ^1.8.0
  mocktail: ^0.3.0

flutter: null
